name: njsscan
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  njsscan:
    runs-on: ubuntu-latest
    name: njsscan code scanning

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: nodejsscan scan
      id: njsscan
      uses: ajinabraham/njsscan-action@master
      with:
        args: '. --sarif --output results.sarif || true'

    - name: Upload njsscan report
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: results.sarif
